apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
    - port: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo:6
        ports:
          - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: devdb
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: devdb@123
        volumeMounts:
          - name: mongo-storage
            mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      labels:
        app: springapp
    spec:
      initContainers:
      - name: wait-for-mongo
        image: busybox
        command:
          - sh
          - -c
          - |
            until nc -z mongo 27017; do
              echo "Waiting for MongoDB..."
              sleep 5
            done
      containers:
      - name: springapp
        image: dockerhandson/spring-boot-mongo
        ports:
          - containerPort: 8080
        env:
          - name: SPRING_DATA_MONGODB_URI
            value: mongodb://devdb:devdb%40123@mongo:27017/admin
---
apiVersion: v1
kind: Service
metadata:
  name: springapp
spec:
  type: NodePort
  selector:
    app: springapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007
